resolver: lts-14.22

packages:
- .

extra-deps:
- ./ghcide/
- ansi-terminal-0.10.2
- base-compat-0.11.0
- cabal-helper-1.0.0.0
- cabal-plan-0.6.2.0
- clock-0.7.2
- fuzzy-0.1.0.0
- haddock-library-1.8.0
- haskell-lsp-0.19.0.0
- haskell-lsp-types-0.19.0.0
- hie-bios-0.3.2
- indexed-profunctors-0.1
- lsp-test-0.10.0.0
- optics-core-0.2
- optparse-applicative-0.15.1.0
- parser-combinators-1.2.1
- regex-base-0.94.0.0
- regex-pcre-builtin-0.95.1.1.8.43
- regex-tdfa-1.3.1.0
- semialign-1.1
- temporary-1.2.1.1
- topograph-1

flags:
  ide:
    pedantic: true

# allow-newer: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
